### ISSUE TITLE
Handling Redis failures

### ISSUE THREAD

**Issue by bmorton** [DmitryTsepelev/graphql-ruby-persisted_queries#16]
I noticed if there's something wrong with making requests to Redis (like an incorrect password, for example), an exception is raised.  I think for my use case I'd like Redis errors to be treated as a cache miss.  I was looking into implementing this at the `RedisStoreAdapter` level with an option for `failures_as_cache_miss` or something similar.

Would you accept a PR for something like this?  Do you have thoughts on how you'd want this implemented?  Or should I build my own Redis adapter for this separately from the gem?

**Comment by bmorton** [comment]
I have a few other ideas that I'd love to implement for this too (including #2 since we're doing this in our production graphql service right now, but only in-memory and not with persisted queries).  Let me know if you're open to discussing some of these features and what the best place for that is.  I'd love to contribute as much as I can!

**Comment by DmitryTsepelev** [comment]
>  I was looking into implementing this at the RedisStoreAdapter level with an option for failures_as_cache_miss or something similar.

I don't mind having it in the `RedisStoreAdapter` since it's going to be configurable. We could even configure an error callback, where user can write something to logs/post a message to the team chat/whatever else. I prefer the current fail-fast behaviour as a default, because incorrect password (or unreliable network) means that something is wrong with the system configuration, and it would be nice to know about it as soon as possible.

> Let me know if you're open to discussing some of these features

Definitely! I'd be happy to help, #2 seems to give a great performance boost, parsing still takes a lot of time for complex queries (here is a related [issue](https://github.com/rmosolgo/graphql-ruby/pull/2572) with benchmark) 💯

**Comment by bmorton** [comment]
Closing this as fixed by #17.  Thanks for merging it!
