### ISSUE TITLE
Instrumentation

### ISSUE THREAD

**Issue by bmorton** [DmitryTsepelev/graphql-ruby-persisted_queries#18]
I’ve been looking at how to tie this gem into our instrumentation framework and I think it might be worth implementing something in the gem that allows an instrumenter to be configured that could accept events for things like “cache miss.” I also have considered ActiveSupport::Notifications to do this, but not sure how you feel about taking a dependency on that (or perhaps an optional dependency).

Have you thought about this? Would you accept a PR for this?

**Comment by DmitryTsepelev** [comment]
I like the idea of having the notification system! I hope someone would use `graphql-ruby` outside the Rails ecosystem and it would be nice to make this work for them. We probably could use a built-in [Tracing](https://graphql-ruby.org/queries/tracing.html) mechanism, since we already have this dependency. What do you think of it?
