### ISSUE TITLE
Doesn't work on graphql (2.2.5)

### ISSUE THREAD

**Issue by Nealsoni00** [DmitryTsepelev/graphql-ruby-persisted_queries#68]
Hey all,

I am working through an upgrade from `graphql (1.13.15)` to `graphql (2.2.5)` on a personal project and i'm running into an issue where APQs are not working anymore. I get an error: `No query string was present` exclusively when I use it now. Any ideas?

Appreciate the help!

**Comment by DmitryTsepelev** [comment]
Hey! 

First of all, please check that you're using the latest version of graphql-ruby-persisted_queries.
After that, please check that hash is properly sent from the client and there's a query in the storage with that hash.

If the issue is still present, could you please build up a sample project from scratch that reproduces the issue?

**Comment by PhilippeChab** [comment]
Works fine for me with 2.2.8.

**Comment by Nealsoni00** [comment]
My bad, this does work. My issue was that I'm working through a migration to graphql-ruby persisted queries (not APQs) and it is hard to get the API to support both at the same time.
